### ISSUE TITLE
isearch-history-next, isearch-history-previous apparently don't work

### ISSUE THREAD

**Issue by evpav** [cursive-ide/emacs-plus#8]
As you can see on the screen shot there are no conflicting actions assigned, yet using the shortcut results in nothing, no matter if the focus is on the search bar or on the editor. There are no related errors in the IDE or in the idea.log. Assigning other shortcuts also doesn't work.
![screenshot_20180815_162659](https://user-images.githubusercontent.com/20708240/44150492-4ea28c0e-a0a8-11e8-9a2f-77cd8001dd25.png)

IDE Info:
Custom plugins: [AceJump (3.5.0), CMD Support (1.0.5), Wrap to Column (1.4.0), Emacs+ Patched (0.3.800), CamelCase (2.0.0), Front End Alignment (1.1), .ignore (3.0.0.182), AsciiDoc (0.20.6), BashSupport (1.6.13.182), PhoneGap/Cordova Plugin (182.2371.6), PHP Class Templates (1.0.2), Php Inspections (EA Extended) (3.0.5.1), PHP Annotations (5.3), deep-assoc-completion (2018.08.15.001), 3v4l pl4g1n (0.4), PHP Advanced AutoComplete (1.0.4), Yii2 Inspections (1.0.3), PHP composer.json support (1.0.25), Lines Sorter (1.0.1), .env files support (0.6)]
Disabled plugins:[Key Promoter X (5.12), Org4Idea (0.4.1), PlantUML integration (2.10.1), Ideolog (182.0.7.0), Navigate Identifier Occurrence (1.1), Emacs+ (0.3.200), CSV Plugin (1.8.0), Pug (ex-Jade) (182.3341.1), Light Bulb Toggle (1.0.1), Stylus support (182.3208.4), Yii2 Support (0.9.54.9), Markdown Navigator (2.5.4), Symfony Plugin (0.16.165)]
Build version: PhpStorm 2018.2.1 Build #PS-182.3911.43 August 8, 2018
Java version: 1.8.0_152-release-1248-b8amd64
Operating System: Linux (4.17.12-1.1-manjaro, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

**Comment by cursive-ghost** [comment]
See [here](https://github.com/cursive-ide/emacs-plus/issues/17#issuecomment-591180410) for some comments on the latest release.
